sudo: false

# Blacklist
branches:
  except:
    - autodocs

# Travis settings
dist: xenial
services:
  - xvfb

# Environment variables
env:
  global:
    - DOXYFILE: $TRAVIS_BUILD_DIR/doxygen.conf
    - GH_REPO_REF: github.com:$TRAVIS_REPO_SLUG.git
    - INSTALL_DIR: $TRAVIS_BUILD_DIR/..
    - SCRIPTS_DIR: $TRAVIS_BUILD_DIR/ci-scripts
    - TRUESTUDIO_TEMP_DIR: $INSTALL_DIR/truestudio
    - DOXYGEN_DIR: $INSTALL_DIR/doxygen
language:
  generic
# Install dependencies
addons:
  apt:
    packages:
      - libwebkitgtk-3.0-0
      - libncurses5
      - libusb-0.1-4
      - libc6-i386
      - at-spi2-core
# Cache downloaded sources, build binaries at runtime

cache:
  directories:
    - $DOXYGEN_DIR
    - $TRUESTUDIO_TEMP_DIR

before_install:
  - export GH_REPO_NAME=$(echo "$TRAVIS_REPO_SLUG" | sed -r 's@.*/(.*)@\1@g')
  - doxygen_new="$DOXYGEN_DIR/build/bin/doxygen"
  - export doxygen_new

# Generate and deploy documentation
script:
  - $SCRIPTS_DIR/doxygen.sh
  - sudo $SCRIPTS_DIR/truestudio.sh
  - $SCRIPTS_DIR/generateDocumentationAndDeploy.sh
