// ------------------------------------------------------------------------------------------------
// Includes

#include <stdint.h>

#include "stm32f4xx.h"
#include "stm32f4xx_hal.h"
#include "FreeRTOS.h"
#include "task.h"

#include "node_tasks.h"
#include "can_tasks.h"
#include "pin_definitions.h"
#include "adc.h"
#include "can.h"
#include "gpio.h"

// ------------------------------------------------------------------------------------------------
// Private function prototypes

static void systemClockConfig(void);

// ------------------------------------------------------------------------------------------------
// Functions

/*
 * @brief   Main program. Initializes peripherals and RTOS tasks, then starts scheduler.
 */
int main(void) {
    // Basic initialization
    HAL_Init();
    systemClockConfig();

    // Peripheral initialization
    gpioInit();

    if (canInit() != HAL_OK) {
        HAL_GPIO_WritePin(mcuStatusLEDPort, mcuStatusLEDPin, SET);
        while (1) {}
    }

    if (adcInit() != HAL_OK) {
        HAL_GPIO_WritePin(mcuStatusLEDPort, mcuStatusLEDPin, SET);
        while (1) {}
    }

    // Node tasks
    xTaskCreate(mcuStatusLED_task, "LED", configMINIMAL_STACK_SIZE, NULL,
                mcuStatusLEDTaskPriority, NULL);
    xTaskCreate(adc_task, "10HZ", configMINIMAL_STACK_SIZE, NULL,
                adcTaskPriority, NULL);

    // CAN tasks
    xTaskCreate(canTX100Hz_task, "TX100HZ", configMINIMAL_STACK_SIZE, NULL,
                canTX100HzTaskPriority, NULL);
    xTaskCreate(canTX10Hz_task, "TX10HZ", configMINIMAL_STACK_SIZE, NULL,
                canTX10HzTaskPriority, NULL);
    xTaskCreate(canRX_task, "CANRX", configMINIMAL_STACK_SIZE, NULL,
                canRXTaskPriority, NULL);

    vTaskStartScheduler();

    while (1) {
        // Shouldn't get here
    }
}

// ------------------------------------------------------------------------------------------------
// Private functions

/**
 * @brief   System Clock Configuration. Generated by STM32Cube.
 *          Sets System Clock to 96 MHz, with only APB1 Peripheral Clocks at 48 MHz.
 */
static void systemClockConfig(void) {
    RCC_OscInitTypeDef RCC_OscInitStruct = { 0 };
    RCC_ClkInitTypeDef RCC_ClkInitStruct = { 0 };

    // Configure the main internal regulator output voltage
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    // Initializes the CPU, AHB and APB busses clocks
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    RCC_OscInitStruct.HSEState = RCC_HSE_ON;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
    RCC_OscInitStruct.PLL.PLLM = 25;
    RCC_OscInitStruct.PLL.PLLN = 192;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
    RCC_OscInitStruct.PLL.PLLQ = 2;
    RCC_OscInitStruct.PLL.PLLR = 2;

    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
        while (1) {}
    }

    // Initializes the CPU, AHB and APB busses clocks
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                                  | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_3) != HAL_OK) {
        while (1) {}
    }
}
