/*
 * This file was autogenerated by OSQP-Python on February 12, 2024 at 18:16:26.
 * 
 * This file contains the workspace variables needed by OSQP.
 */

#include "types.h"
#include "qdldl_interface.h"

// Define data structure
c_int Pdata_p[5] = {
0,
1,
3,
6,
10,
};
c_int Pdata_i[10] = {
0,
0,
1,
0,
1,
2,
0,
1,
2,
3,
};
c_float Pdata_x[10] = {
(c_float)0.93855960640520996741,
(c_float)-0.50199850696095871250,
(c_float)0.93855960640520996741,
(c_float)0.93853777944158611746,
(c_float)-0.50199850696095871250,
(c_float)0.93855960640520996741,
(c_float)-0.50199850696095871250,
(c_float)0.93853777944158611746,
(c_float)-0.50199850696095871250,
(c_float)0.93855960640520996741,
};
csc Pdata = {10, 4, 4, Pdata_p, Pdata_i, Pdata_x, -1};
c_int Adata_p[5] = {
0,
2,
4,
6,
8,
};
c_int Adata_i[8] = {
0,
4,
1,
4,
2,
4,
3,
4,
};
c_float Adata_x[8] = {
(c_float)0.99357813279100315462,
(c_float)1.00000000000000000000,
(c_float)0.99357813279100315462,
(c_float)1.00000000000000000000,
(c_float)0.99357813279100315462,
(c_float)1.00000000000000000000,
(c_float)0.99357813279100315462,
(c_float)1.00000000000000000000,
};
csc Adata = {8, 5, 4, Adata_p, Adata_i, Adata_x, -1};
c_float qdata[4] = {
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
};
c_float ldata[5] = {
(c_float)-516.94066514358553376951,
(c_float)-516.94066514358553376951,
(c_float)-516.94066514358553376951,
(c_float)-516.94066514358553376951,
(c_float)0.00000000000000000000,
};
c_float udata[5] = {
(c_float)516.94066514358553376951,
(c_float)516.94066514358553376951,
(c_float)516.94066514358553376951,
(c_float)516.94066514358553376951,
(c_float)2954.79025475794924204820,
};
OSQPData data = {4, 5, &Pdata, &Adata, qdata, ldata, udata};

// Define settings structure
OSQPSettings settings = {(c_float)0.10000000000000000555, (c_float)0.00000100000000000000, 10, 0, 0, (c_float)5.00000000000000000000, 20000, (c_float)0.00100000000000000002, (c_float)0.00100000000000000002, (c_float)0.00010000000000000000, (c_float)0.00010000000000000000, (c_float)1.60000000000000008882, (enum linsys_solver_type) LINSYS_SOLVER, 0, 25, 1, };

// Define scaling structure
c_float Dscaling[4] = {
(c_float)0.03693487818447436372,
(c_float)0.03693487818447436372,
(c_float)0.03693487818447436372,
(c_float)0.03693487818447436372,
};
c_float Dinvscaling[4] = {
(c_float)27.07467979196833240962,
(c_float)27.07467979196833240962,
(c_float)27.07467979196833240962,
(c_float)27.07467979196833240962,
};
c_float Escaling[5] = {
(c_float)26.90080979361820467943,
(c_float)26.90080979361820467943,
(c_float)26.90080979361820467943,
(c_float)26.90080979361820467943,
(c_float)0.03693487818447436372,
};
c_float Einvscaling[5] = {
(c_float)0.03717360212097534089,
(c_float)0.03717360212097534089,
(c_float)0.03717360212097534089,
(c_float)0.03717360212097534089,
(c_float)27.07467979196833240962,
};
OSQPScaling scaling = {(c_float)1.00000000000000000000, Dscaling, Escaling, (c_float)1.00000000000000000000, Dinvscaling, Einvscaling};

// Define linsys_solver structure
c_int linsys_solver_L_p[10] = {
0,
1,
2,
3,
4,
8,
11,
13,
14,
14,
};
c_int linsys_solver_L_i[14] = {
8,
4,
5,
6,
5,
6,
7,
8,
6,
7,
8,
7,
8,
8,
};
c_float linsys_solver_L_x[14] = {
(c_float)-0.09935781327910031546,
(c_float)-0.09935781327910031546,
(c_float)-0.09935781327910031546,
(c_float)-0.09935781327910031546,
(c_float)-0.48395643817281985832,
(c_float)0.90480627836708371614,
(c_float)0.96405951703449588308,
(c_float)-0.48395643817281985832,
(c_float)-0.06015989385321993815,
(c_float)1.86817468203847814046,
(c_float)0.87569151041702453231,
(c_float)0.99599250285198848154,
(c_float)-0.03207344785595607484,
(c_float)-0.01367700050230337590,
};
csc linsys_solver_L = {14, 9, 9, linsys_solver_L_p, linsys_solver_L_i, linsys_solver_L_x, -1};
c_float linsys_solver_Dinv[9] = {
(c_float)-0.10000000000000000555,
(c_float)-0.10000000000000000555,
(c_float)-0.10000000000000000555,
(c_float)-0.10000000000000000555,
(c_float)0.96405951703449588308,
(c_float)1.25891477268614582208,
(c_float)5.39925858458279162022,
(c_float)-0.07183867538154166399,
(c_float)5.32980906977343771302,
};
c_int linsys_solver_P[9] = {
4,
5,
6,
7,
1,
2,
3,
8,
0,
};
c_float linsys_solver_bp[9];
c_float linsys_solver_sol[9];
c_float linsys_solver_rho_inv_vec[5] = {
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
};
c_int linsys_solver_Pdiag_idx[4] = {
0,
2,
5,
9,
};
c_int linsys_solver_KKT_p[10] = {
0,
1,
2,
3,
4,
6,
9,
13,
17,
23,
};
c_int linsys_solver_KKT_i[23] = {
0,
1,
2,
3,
4,
1,
4,
5,
2,
4,
5,
6,
3,
4,
5,
6,
7,
8,
4,
5,
6,
0,
7,
};
c_float linsys_solver_KKT_x[23] = {
(c_float)-10.00000000000000000000,
(c_float)-10.00000000000000000000,
(c_float)-10.00000000000000000000,
(c_float)-10.00000000000000000000,
(c_float)0.93856060640520999616,
(c_float)0.99357813279100315462,
(c_float)-0.50199850696095871250,
(c_float)0.93856060640520999616,
(c_float)0.99357813279100315462,
(c_float)0.93853777944158611746,
(c_float)-0.50199850696095871250,
(c_float)0.93856060640520999616,
(c_float)0.99357813279100315462,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)-10.00000000000000000000,
(c_float)0.93856060640520999616,
(c_float)-0.50199850696095871250,
(c_float)0.93853777944158611746,
(c_float)-0.50199850696095871250,
(c_float)0.99357813279100315462,
(c_float)1.00000000000000000000,
};
csc linsys_solver_KKT = {23, 9, 9, linsys_solver_KKT_p, linsys_solver_KKT_i, linsys_solver_KKT_x, -1};
c_int linsys_solver_PtoKKT[10] = {
17,
18,
4,
19,
6,
7,
20,
9,
10,
11,
};
c_int linsys_solver_AtoKKT[8] = {
21,
22,
5,
13,
8,
14,
12,
15,
};
c_int linsys_solver_rhotoKKT[5] = {
0,
1,
2,
3,
16,
};
QDLDL_float linsys_solver_D[9] = {
-10,
-10,
-10,
-10,
1,
0,
0,
-13,
0,
};
QDLDL_int linsys_solver_etree[9] = {
8,
4,
5,
6,
5,
6,
7,
8,
-1,
};
QDLDL_int linsys_solver_Lnz[9] = {
1,
1,
1,
1,
4,
3,
2,
1,
0,
};
QDLDL_int   linsys_solver_iwork[27];
QDLDL_bool  linsys_solver_bwork[9];
QDLDL_float linsys_solver_fwork[9];
qdldl_solver linsys_solver = {QDLDL_SOLVER, &solve_linsys_qdldl, &update_linsys_solver_matrices_qdldl, &update_linsys_solver_rho_vec_qdldl, &linsys_solver_L, linsys_solver_Dinv, linsys_solver_P, linsys_solver_bp, linsys_solver_sol, linsys_solver_rho_inv_vec, (c_float)0.00000100000000000000, 4, 5, linsys_solver_Pdiag_idx, 4, &linsys_solver_KKT, linsys_solver_PtoKKT, linsys_solver_AtoKKT, linsys_solver_rhotoKKT, linsys_solver_D, linsys_solver_etree, linsys_solver_Lnz, linsys_solver_iwork, linsys_solver_bwork, linsys_solver_fwork, };

// Define solution
c_float xsolution[4];
c_float ysolution[5];

OSQPSolution solution = {xsolution, ysolution};

// Define info
OSQPInfo info = {0, "Unsolved", OSQP_UNSOLVED, 0.0, 0.0, 0.0};

// Define workspace
c_float work_rho_vec[5] = {
(c_float)0.10000000000000000555,
(c_float)0.10000000000000000555,
(c_float)0.10000000000000000555,
(c_float)0.10000000000000000555,
(c_float)0.10000000000000000555,
};
c_float work_rho_inv_vec[5] = {
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
};
c_int work_constr_type[5] = {
0,
0,
0,
0,
0,
};
c_float work_x[4];
c_float work_y[5];
c_float work_z[5];
c_float work_xz_tilde[9];
c_float work_x_prev[4];
c_float work_z_prev[5];
c_float work_Ax[5];
c_float work_Px[4];
c_float work_Aty[4];
c_float work_delta_y[5];
c_float work_Atdelta_y[4];
c_float work_delta_x[4];
c_float work_Pdelta_x[4];
c_float work_Adelta_x[5];
c_float work_D_temp[4];
c_float work_D_temp_A[4];
c_float work_E_temp[5];

OSQPWorkspace workspace = {
&data, (LinSysSolver *)&linsys_solver,
work_rho_vec, work_rho_inv_vec,
work_constr_type,
work_x, work_y, work_z, work_xz_tilde,
work_x_prev, work_z_prev,
work_Ax, work_Px, work_Aty,
work_delta_y, work_Atdelta_y,
work_delta_x, work_Pdelta_x, work_Adelta_x,
work_D_temp, work_D_temp_A, work_E_temp,
&settings, &scaling, &solution, &info};

