# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "C:/Users/nosla/Downloads/monorepo/RAM;C:/Users/nosla/Downloads/monorepo/RAM/Src/RAM-build")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "C:/ST/STM32CubeCLT_1.16.0/CMake/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "RAM built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "TGZ")
set(CPACK_IGNORE_FILES "/\\.git/;/cntest/;/new\\.out/;/.*\\.o/;/build/;/CMakeLists\\.txt\\.user/;/CMakeCache\\.txt/;/CMakeFiles/;/CMakeScripts/;/Testing/;/Makefile/;/cmake_install\\.cmake/;/install_manifest\\.txt/;/compile_commands\\.json/;/CTestTestfile\\.cmake/;/_deps/;/CMakeUserPresets\\.json/")
set(CPACK_INNOSETUP_ARCHITECTURE "x86")
set(CPACK_INSTALLED_DIRECTORIES "C:/Users/nosla/Downloads/monorepo/RAM;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/RAM")
set(CPACK_MODULE_PATH "{{sr:cmake_path}}")
set(CPACK_NSIS_DISPLAY_NAME "RAM 0.1.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "RAM 0.1.0")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "arm-none-eabi-objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "C:/ST/STM32CubeCLT_1.16.0/GNU-tools-for-STM32/bin/arm-none-eabi-objdump.exe")
set(CPACK_OUTPUT_CONFIG_FILE "C:/Users/nosla/Downloads/monorepo/RAM/Src/RAM-build/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Users/nosla/Downloads/monorepo/RAM/cn-cbor/README.md")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "RAM built using CMake")
set(CPACK_PACKAGE_FILE_NAME "RAM-0.1.0-Source")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "RAM 0.1.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "RAM 0.1.0")
set(CPACK_PACKAGE_NAME "RAM")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Humanity")
set(CPACK_PACKAGE_VERSION "0.1.0")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_READELF_EXECUTABLE "C:/ST/STM32CubeCLT_1.16.0/GNU-tools-for-STM32/bin/arm-none-eabi-readelf.exe")
set(CPACK_RESOURCE_FILE_LICENSE "C:/Users/nosla/Downloads/monorepo/RAM/cn-cbor/LICENSE")
set(CPACK_RESOURCE_FILE_README "C:/ST/STM32CubeCLT_1.16.0/CMake/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "C:/ST/STM32CubeCLT_1.16.0/CMake/share/cmake-3.28/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_SOURCE_IGNORE_FILES "/\\.git/;/cntest/;/new\\.out/;/.*\\.o/;/build/;/CMakeLists\\.txt\\.user/;/CMakeCache\\.txt/;/CMakeFiles/;/CMakeScripts/;/Testing/;/Makefile/;/cmake_install\\.cmake/;/install_manifest\\.txt/;/compile_commands\\.json/;/CTestTestfile\\.cmake/;/_deps/;/CMakeUserPresets\\.json/")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "C:/Users/nosla/Downloads/monorepo/RAM;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "C:/Users/nosla/Downloads/monorepo/RAM/Src/RAM-build/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "RAM-0.1.0-Source")
set(CPACK_SOURCE_TOPLEVEL_TAG "Generic-Source")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Generic")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Generic-Source")
set(CPACK_WIX_SIZEOF_VOID_P "4")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "C:/Users/nosla/Downloads/monorepo/RAM/Src/RAM-build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
