/**
 * @file rcc.c
 * @brief Reset and clock controller wrapper implementation.
 *
 * @author Carnegie Mellon Racing
 */

#include "rcc.h"    // Interface to implement
#include "panic.h"  // cmr_panic()

#ifdef HAL_RCC_MODULE_ENABLED

/**
 * @brief Configures the system and peripheral clocks.
 *
 * @note Generated by STM32Cube. Sets System Clock to 96 MHz, with only APB1
 * Peripheral Clocks at 48 MHz.
 */
void cmr_rccSystemClockEnable(void)  {
    RCC_OscInitTypeDef RCC_OscInitStruct = { 0 };
    RCC_ClkInitTypeDef RCC_ClkInitStruct = { 0 };

    // Configure the main internal regulator output voltage
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    // Initializes the CPU, AHB and APB busses clocks
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    RCC_OscInitStruct.HSEState = RCC_HSE_ON;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
    RCC_OscInitStruct.PLL.PLLM = 25;
    RCC_OscInitStruct.PLL.PLLN = 192;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
    RCC_OscInitStruct.PLL.PLLQ = 2;
    RCC_OscInitStruct.PLL.PLLR = 2;

    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
        cmr_panic("HAL_RCC_OscConfig() failed!");
    }

    // Initializes the CPU, AHB and APB busses clocks
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                                  | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_3) != HAL_OK) {
        cmr_panic("HAL_RCC_ClockConfig() failed!");
    }
}

#ifdef HAL_GPIO_MODULE_ENABLED
/**
 * @brief Enables the specified GPIO port's clock.
 *
 * @param port The GPIO port.
 */
void cmr_rccGPIOClockEnable(GPIO_TypeDef *port) {
    switch (port) {
        case GPIOA:
            __HAL_RCC_GPIOA_CLK_ENABLE();
            break;
        case GPIOB:
            __HAL_RCC_GPIOB_CLK_ENABLE();
            break;
        case GPIOC:
            __HAL_RCC_GPIOC_CLK_ENABLE();
            break;
        case GPIOD:
            __HAL_RCC_GPIOD_CLK_ENABLE();
            break;
        case GPIOE:
            __HAL_RCC_GPIOE_CLK_ENABLE();
            break;
        case GPIOF:
            __HAL_RCC_GPIOF_CLK_ENABLE();
            break;
        case GPIOG:
            __HAL_RCC_GPIOG_CLK_ENABLE();
            break;
        case GPIOH:
            __HAL_RCC_GPIOH_CLK_ENABLE();
            break;
    }
}
#endif /* HAL_GPIO_MODULE_ENABLED */

#ifdef HAL_ADC_MODULE_ENABLED
/**
 * @brief Enables the specified ADC's clock.
 *
 * @param instance The HAL ADC instance.
 */
void cmr_rccADCClockEnable(ADC_TypeDef *instance) {
    switch (instance) {
        case ADC1:
            __HAL_RCC_ADC1_CLK_ENABLE();
            break;
    }
}
#endif /* HAL_ADC_MODULE_ENABLED */

#ifdef HAL_CAN_MODULE_ENABLED
/**
 * @brief Enables the specified CAN interface's clock.
 *
 * @param instance The HAL CAN instance.
 */
void cmr_rccCANClockEnable(CAN_TypeDef *instance) {
    switch (instance) {
        case CAN3:
            __HAL_RCC_CAN3_CLK_ENABLE();
            break;
        case CAN2:
            __HAL_RCC_CAN2_CLK_ENABLE();
            // Fallthrough; CAN2 also requires CAN1 clock.
        case CAN1:
            __HAL_RCC_CAN1_CLK_ENABLE();
            break;
    }
}
#endif /* HAL_CAN_MODULE_ENABLED */

#endif /* HAL_RCC_MODULE_ENABLED */

