/**
 * @file rcc.c
 * @brief Reset and clock controller wrapper implementation.
 *
 * @author Carnegie Mellon Racing
 */

#include "rcc.h"    // Interface to implement
#include "panic.h"  // cmr_panic()

#ifdef HAL_RCC_MODULE_ENABLED

/**
 * @brief Configures the system and peripheral clocks, using
 * an external clock.
 *
 * @note Generated by STM32Cube. Sets System Clock to 96 MHz, with only APB1
 * Peripheral Clocks at 48 MHz (APB1 Timer Clocks are still 96 MHz).
 */
void cmr_rccSystemClockEnable(void)  {
      RCC_OscInitTypeDef RCC_OscInitStruct = {0};
      RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
      RCC_PeriphCLKInitTypeDef PeriphClkInit = {0};

      /** Initializes the CPU, AHB and APB busses clocks
      */
      RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
      RCC_OscInitStruct.HSIState = RCC_HSI_ON;
      RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
      RCC_OscInitStruct.PLL.PLLState = RCC_PLL_NONE;
      if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
      {
          cmr_panic("HAL_RCC_OscConfig() failed!");
      }
      /** Initializes the CPU, AHB and APB busses clocks
      */
      RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                                  |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
      RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_HSI;
      RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
      RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
      RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

      if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0) != HAL_OK)
      {
          cmr_panic("HAL_RCC_OscConfig() failed!");
      }
      PeriphClkInit.PeriphClockSelection = RCC_PERIPHCLK_ADC;
      PeriphClkInit.AdcClockSelection = RCC_ADCCLKSOURCE_SYSCLK;
      if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInit) != HAL_OK)
      {
          cmr_panic("HAL_RCC_OscConfig() failed!");
      }
      /** Configure the main internal regulator output voltage
      */
      if (HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1) != HAL_OK)
      {
          cmr_panic("HAL_RCC_OscConfig() failed!");
      }
}

/**
 * @brief Configures the system and peripheral clocks,
 * using an internal clock.
 *
 * @note Generated by STM32Cube. Sets System Clock to 16 MHz.
 */
void cmr_rccSystemInternalClockEnable(void)  {
    RCC_OscInitTypeDef RCC_OscInitStruct = { 0 };
    RCC_ClkInitTypeDef RCC_ClkInitStruct = { 0 };
    RCC_PeriphCLKInitTypeDef PeriphClkInit = {0};

    // Configure the main internal regulator output voltage
    //__HAL_RCC_PWR_CLK_ENABLE();
    //__HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    // Initializes the CPU, AHB and APB busses clocks
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
    RCC_OscInitStruct.PLL.PLLM = 1;
    RCC_OscInitStruct.PLL.PLLN = 20;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV7;
    RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
    RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV4;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
        cmr_panic("HAL_RCC_OscConfig() failed!");
    }

    // Initializes the CPU, AHB and APB busses clocks
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                                |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
    if(HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4) != HAL_OK) {
        cmr_panic("HAL_RCC_OscConfig() failed!");
    }

    PeriphClkInit.PeriphClockSelection = RCC_PERIPHCLK_ADC;
    PeriphClkInit.AdcClockSelection = RCC_ADCCLKSOURCE_PLLSAI1;
    PeriphClkInit.PLLSAI1.PLLSAI1Source = RCC_PLLSOURCE_HSI;
    PeriphClkInit.PLLSAI1.PLLSAI1M = 1;
    PeriphClkInit.PLLSAI1.PLLSAI1N = 8;
    PeriphClkInit.PLLSAI1.PLLSAI1P = RCC_PLLP_DIV7;
    PeriphClkInit.PLLSAI1.PLLSAI1Q = RCC_PLLQ_DIV2;
    PeriphClkInit.PLLSAI1.PLLSAI1R = RCC_PLLR_DIV8;
    PeriphClkInit.PLLSAI1.PLLSAI1ClockOut = RCC_PLLSAI1_ADC1CLK;
    if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInit) != HAL_OK)
    {
        cmr_panic("HAL_RCC_PeriphCLKConfig() failed!");
    }

    /** Configure the main internal regulator output voltage
    */
    if (HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1) != HAL_OK)
    {
        cmr_panic("HAL_RCC_ControlVoltageScaling() failed!");
    }
}

#ifdef HAL_GPIO_MODULE_ENABLED
/**
 * @brief Enables the specified GPIO port's clock.
 *
 * @param port The GPIO port.
 */
void cmr_rccGPIOClockEnable(GPIO_TypeDef *port) {
    switch ((uintptr_t) port) {
        case GPIOA_BASE:
            __HAL_RCC_GPIOA_CLK_ENABLE();
            break;
        case GPIOB_BASE:
            __HAL_RCC_GPIOB_CLK_ENABLE();
            break;
        case GPIOC_BASE:
            __HAL_RCC_GPIOC_CLK_ENABLE();
            break;
        case GPIOD_BASE:
            __HAL_RCC_GPIOD_CLK_ENABLE();
            break;
        case GPIOE_BASE:
            __HAL_RCC_GPIOE_CLK_ENABLE();
            break;
        case GPIOH_BASE:
            __HAL_RCC_GPIOH_CLK_ENABLE();
            break;
    }
}
#endif /* HAL_GPIO_MODULE_ENABLED */

#ifdef HAL_ADC_MODULE_ENABLED
/**
 * @brief Enables the specified ADC's clock.
 *
 * @param instance The HAL ADC instance.
 */
void cmr_rccADCClockEnable(ADC_TypeDef *instance) {
    switch ((uintptr_t) instance) {
        case ADC1_BASE:
            __HAL_RCC_ADC_CLK_ENABLE();
            break;
    }
}
#endif /* HAL_ADC_MODULE_ENABLED */

#ifdef HAL_CAN_MODULE_ENABLED
/**
 * @brief Enables the specified CAN interface's clock.
 *
 * @param instance The HAL CAN instance.
 */
void cmr_rccCANClockEnable(CAN_TypeDef *instance) {
    switch ((uintptr_t) instance) {
        case CAN1_BASE:
            __HAL_RCC_CAN1_CLK_ENABLE();
            break;
    }
}
#endif /* HAL_CAN_MODULE_ENABLED */

#ifdef HAL_I2C_MODULE_ENABLED
/**
 * @brief Enables the specified I2C port's clock.
 *
 * @param instance The HAL I2C instance.
 */
void cmr_rccI2CClockEnable(I2C_TypeDef *instance) {
    switch ((uintptr_t) instance) {
        case I2C1_BASE:
            __HAL_RCC_I2C1_CLK_ENABLE();
            break;
        case I2C2_BASE:
            __HAL_RCC_I2C2_CLK_ENABLE();
            break;
        case I2C3_BASE:
            __HAL_RCC_I2C3_CLK_ENABLE();
            break;
    }
}
#endif /* HAL_I2C_MODULE_ENABLED */

#ifdef HAL_SPI_MODULE_ENABLED
/**
 * @brief Enables the specified SPI port's clock.
 *
 * @param instance The HAL SPI instance.
 */
void cmr_rccSPIClockEnable(SPI_TypeDef *instance) {
    switch ((uintptr_t) instance) {
        case SPI1_BASE:
            __HAL_RCC_SPI1_CLK_ENABLE();
            break;
        case SPI2_BASE:
            __HAL_RCC_SPI2_CLK_ENABLE();
            break;
        case SPI3_BASE:
            __HAL_RCC_SPI3_CLK_ENABLE();
            break;
        case SPI4_BASE:
            __HAL_RCC_SPI4_CLK_ENABLE();
            break;
        case SPI5_BASE:
            __HAL_RCC_SPI5_CLK_ENABLE();
            break;
    }
}
#endif /* HAL_SPI_MODULE_ENABLED */

#ifdef HAL_QSPI_MODULE_ENABLED
/**
 * @brief Enables the specified QuadSPI port's clock.
 *
 * @param instance The HAL QUADSPI instance.
 */
void cmr_rccQSPIClockEnable(QUADSPI_TypeDef *instance) {
    __HAL_RCC_QSPI_CLK_ENABLE();
}
#endif /* HAL_QSPI_MODULE_ENABLED */

#ifdef HAL_USART_MODULE_ENABLED
/**
 * @brief Enables the specified USART interface's clock.
 *
 * @param instance The HAL USART instance.
 */
void cmr_rccUSARTClockEnable(USART_TypeDef *instance) {
    switch ((uintptr_t) instance) {
        case USART1_BASE:
            __HAL_RCC_USART1_CLK_ENABLE();
            return;
        case USART2_BASE:
            __HAL_RCC_USART2_CLK_ENABLE();
            return;
        case USART3_BASE:
            __HAL_RCC_USART3_CLK_ENABLE();
            return;
        case UART4_BASE:
            __HAL_RCC_UART4_CLK_ENABLE();
            return;
        case UART5_BASE:
            __HAL_RCC_UART5_CLK_ENABLE();
            return;
        case USART6_BASE:
            __HAL_RCC_USART6_CLK_ENABLE();
            return;
        case UART7_BASE:
            __HAL_RCC_UART7_CLK_ENABLE();
            return;
        case UART8_BASE:
            __HAL_RCC_UART8_CLK_ENABLE();
            return;
        case UART9_BASE:
            __HAL_RCC_UART9_CLK_ENABLE();
            return;
        case UART10_BASE:
            __HAL_RCC_UART10_CLK_ENABLE();
            return;
    }
}
#endif /* HAL_USART_MODULE_ENABLED */

#ifdef HAL_TIM_MODULE_ENABLED
void cmr_rccTIMClockEnable(TIM_TypeDef *instance) {
    switch ((uintptr_t) instance) {
        case TIM1_BASE:
            __HAL_RCC_TIM1_CLK_ENABLE();
            break;
        case TIM2_BASE:
            __HAL_RCC_TIM2_CLK_ENABLE();
            break;
        case TIM3_BASE:
            __HAL_RCC_TIM3_CLK_ENABLE();
            break;
        case TIM4_BASE:
            __HAL_RCC_TIM4_CLK_ENABLE();
            break;
        case TIM5_BASE:
            __HAL_RCC_TIM5_CLK_ENABLE();
            break;
        case TIM6_BASE:
            __HAL_RCC_TIM6_CLK_ENABLE();
            break;
        case TIM7_BASE:
            __HAL_RCC_TIM7_CLK_ENABLE();
            break;
        case TIM8_BASE:
            __HAL_RCC_TIM8_CLK_ENABLE();
            break;
        case TIM9_BASE:
            __HAL_RCC_TIM9_CLK_ENABLE();
            break;
        case TIM10_BASE:
            __HAL_RCC_TIM10_CLK_ENABLE();
            break;
        case TIM11_BASE:
            __HAL_RCC_TIM11_CLK_ENABLE();
            break;
        case TIM12_BASE:
            __HAL_RCC_TIM12_CLK_ENABLE();
            break;
        case TIM13_BASE:
            __HAL_RCC_TIM13_CLK_ENABLE();
            break;
        case TIM14_BASE:
            __HAL_RCC_TIM14_CLK_ENABLE();
            break;
    }
}
#endif /* HAL_TIM_MODULE_ENABLED */

#endif /* HAL_RCC_MODULE_ENABLED */

