/**
 * @file rcc.c
 * @brief Reset and clock controller wrapper implementation.
 *
 * @author Carnegie Mellon Racing
 */

#include "rcc.h"    // Interface to implement
#include "panic.h"  // cmr_panic()

#ifdef HAL_RCC_MODULE_ENABLED

/**
 * @brief Configures the system and peripheral clocks.
 *
 * @note Generated by STM32Cube. Sets System Clock to 96 MHz, with only APB1
 * Peripheral Clocks at 48 MHz.
 */
void cmr_rccSystemClockEnable(void)  {
    RCC_OscInitTypeDef RCC_OscInitStruct = { 0 };
    RCC_ClkInitTypeDef RCC_ClkInitStruct = { 0 };

    // Configure the main internal regulator output voltage
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    // Initializes the CPU, AHB and APB busses clocks
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    RCC_OscInitStruct.HSEState = RCC_HSE_ON;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
    RCC_OscInitStruct.PLL.PLLM = 25;
    RCC_OscInitStruct.PLL.PLLN = 192;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
    RCC_OscInitStruct.PLL.PLLQ = 2;
    RCC_OscInitStruct.PLL.PLLR = 2;

    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
        cmr_panic("HAL_RCC_OscConfig() failed!");
    }

    // Initializes the CPU, AHB and APB busses clocks
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                                  | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_3) != HAL_OK) {
        cmr_panic("HAL_RCC_ClockConfig() failed!");
    }
}

#ifdef HAL_GPIO_MODULE_ENABLED
/**
 * @brief Enables the specified GPIO port's clock.
 *
 * @param port The GPIO port.
 */
void cmr_rccGPIOClockEnable(GPIO_TypeDef *port) {
    if (port == GPIOA) {
        __HAL_RCC_GPIOA_CLK_ENABLE();
        return;
    }
    if (port == GPIOB) {
        __HAL_RCC_GPIOB_CLK_ENABLE();
        return;
    }
    if (port == GPIOC) {
        __HAL_RCC_GPIOC_CLK_ENABLE();
        return;
    }
    if (port == GPIOD) {
        __HAL_RCC_GPIOD_CLK_ENABLE();
        return;
    }
    if (port == GPIOE) {
        __HAL_RCC_GPIOE_CLK_ENABLE();
        return;
    }
    if (port == GPIOF) {
        __HAL_RCC_GPIOF_CLK_ENABLE();
        return;
    }
    if (port == GPIOG) {
        __HAL_RCC_GPIOG_CLK_ENABLE();
        return;
    }
    if (port == GPIOH) {
        __HAL_RCC_GPIOH_CLK_ENABLE();
        return;
    }
}
#endif /* HAL_GPIO_MODULE_ENABLED */

#ifdef HAL_ADC_MODULE_ENABLED
/**
 * @brief Enables the specified ADC's clock.
 *
 * @param instance The HAL ADC instance.
 */
void cmr_rccADCClockEnable(ADC_TypeDef *instance) {
    if (instance == ADC1) {
        __HAL_RCC_ADC1_CLK_ENABLE();
        return;
    }
}
#endif /* HAL_ADC_MODULE_ENABLED */

#ifdef HAL_CAN_MODULE_ENABLED
/**
 * @brief Enables the specified CAN interface's clock.
 *
 * @param instance The HAL CAN instance.
 */
void cmr_rccCANClockEnable(CAN_TypeDef *instance) {
    if (instance == CAN3) {
        __HAL_RCC_CAN3_CLK_ENABLE();
        return;
    }
    if (instance == CAN2) {
        __HAL_RCC_CAN2_CLK_ENABLE();
        __HAL_RCC_CAN1_CLK_ENABLE();    // CAN2 also needs CAN1 clock.
        return;
    }
    if (instance == CAN1) {
        __HAL_RCC_CAN1_CLK_ENABLE();
        return;
    }
}
#endif /* HAL_CAN_MODULE_ENABLED */

#ifdef HAL_SPI_MODULE_ENABLED
/**
 * @brief Enables the specified SPI port's clock.
 *
 * @param instance The HAL SPI instance.
 */
void cmr_rccSPIClockEnable(SPI_TypeDef *instance) {
    if (instance == SPI1) {
        __HAL_RCC_SPI1_CLK_ENABLE();
        return;
    }
    if (instance == SPI2) {
        __HAL_RCC_SPI2_CLK_ENABLE();
        return;
    }
    if (instance == SPI3) {
        __HAL_RCC_SPI3_CLK_ENABLE();
        return;
    }
    if (instance == SPI4) {
        __HAL_RCC_SPI4_CLK_ENABLE();
        return;
    }
    if (instance == SPI5) {
        __HAL_RCC_SPI5_CLK_ENABLE();
        return;
    }
}
#endif /* HAL_SPI_MODULE_ENABLED */

#ifdef HAL_USART_MODULE_ENABLED
/**
 * @brief Enables the specified USART interface's clock.
 *
 * @param instance The HAL USART instance.
 */
void cmr_rccUSARTClockEnable(USART_TypeDef *instance) {
    switch ((uintptr_t) instance) {
        case USART1_BASE:
            __HAL_RCC_USART1_CLK_ENABLE();
            return;
        case USART2_BASE:
            __HAL_RCC_USART2_CLK_ENABLE();
            return;
        case USART3_BASE:
            __HAL_RCC_USART3_CLK_ENABLE();
            return;
        case UART4_BASE:
            __HAL_RCC_UART4_CLK_ENABLE();
            return;
        case UART5_BASE:
            __HAL_RCC_UART5_CLK_ENABLE();
            return;
        case USART6_BASE:
            __HAL_RCC_USART6_CLK_ENABLE();
            return;
        case UART7_BASE:
            __HAL_RCC_UART7_CLK_ENABLE();
            return;
        case UART8_BASE:
            __HAL_RCC_UART8_CLK_ENABLE();
            return;
        case UART9_BASE:
            __HAL_RCC_UART9_CLK_ENABLE();
            return;
        case UART10_BASE:
            __HAL_RCC_UART10_CLK_ENABLE();
            return;
    }
}
#endif /* HAL_USART_MODULE_ENABLED */

#endif /* HAL_RCC_MODULE_ENABLED */

