
name: Build
run-name: ${{ github.actor }}-${{github.repository}} Build 🚀

on: pull_request

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Build Project
        uses: threeal/cmake-action@v2.0.0
