
name: Build
run-name: ${{ github.actor }} Build 🚀

on: pull_request

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  build:
    runs-on: [self-hosted,linux]
    steps:
      - uses: actions/checkout@v3.6.0
        with:
          # check out HEAD on the branch
          ref: ${{ github.head_ref }}
          # Feature just to grab the branch in newer version
          fetch-depth: 1
      - run: ${GITHUB_WORKSPACE}/build.sh
