
name: Build
run-name: ${{ github.actor }}-${{github.repository}} Build 🚀

on: pull_request

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  build:
    runs-on: [self-hosted,linux]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Build Project
        uses: threeal/cmake-action@v2.0.0
