name: Run Python Symbol File Generation Scripts

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  run-symfilegen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run symbol file generation scripts
        run: |
          echo "Running symbol file scripts in sequence"
          echo "Running symbol file scripts in sequence"
          python stm32f413-drivers/filegen/canid_mapper.py
          python stm32f413-drivers/filegen/extra_info.py
          python stm32f413-drivers/filegen/sym_gen.py
          python stm32f413-drivers/filegen/merge_can_signals.py
          python stm32f413-drivers/filegen/enum_generator.py

      - name: Commit and push generated .sym files (if unprotected branch)
        if: github.ref_name != 'main'
        run: |
          echo "Unprotected branch. Committing generated files."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stm32f413-drivers/PCAN/*.sym
          git commit -m "Auto-generate symbol files [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF_NAME}
