name: Build OpenBLT Project
run-name: ${{ github.actor }}-${{ github.repository }} Build

on:
  push:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: linux-binary
          - os: windows-latest
            artifact_name: windows-binary
          - os: macos-latest
            artifact_name: macos-binary

    defaults:
      run:
        working-directory: ./BOOT/Host  # Replace with your custom subfolder path

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev
        
      - name: Configure CMake
        run: cmake --preset release

      - name: Build Project
        run: cmake --build --preset release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            ./build/release/Release/FlashCli   # Linux/macOS path
            ./build/release/Release/*.exe    # Windows path (adjust as needed)
