name: Static Analysis
run-name: ${{ github.actor }}-${{github.repository}} Static Analysis

on:
    workflow_dispatch:
    schedule:
      - cron: "0 8 * * *"   # 8am GMT 4am EST daily

jobs:
  build:
    runs-on: self-hosted
    permissions:
      security-events: write # Required to upload SARIF files
      actions: read          # Recommended for checkout action
      contents: read         # Recommended for checkout action
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
            options: CMAKE_BUILD_TYPE=Static
            # Keep parity with how vscode handles builds
            build-dir: ${{ github.workspace }}/build/static

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install SARIF tools
        run: pip install sarif-tools

      - name: Merge SARIF files
        run: python scripts/merge_sarif.py

        # This find and replace can be removed once we transition to GCC 15 unless the fix is backported
      - name: Fix SARIF schema compatibility
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '"startColumn": 0,'
          replace: '"startColumn": 1,'
          include: "**sarif"
          exclude: . # Do not modify this file
          regex: false

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        if: success()
        with:
          sarif_file: ${{ github.workspace }}/build/sarif
          category: gcc-analysis
