name: Static Analysis
run-name: ${{ github.actor }}-${{github.repository}} Static Analysis

on:
    workflow_dispatch:
    schedule:
      - cron: "0 4 * * *"   # <=== Change this value

jobs:
  build:
    runs-on: self-hosted
    permissions:
      security-events: write # Required to upload SARIF files
      actions: read          # Recommended for checkout action
      contents: read         # Recommended for checkout action
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
            options: CMAKE_BUILD_TYPE=Static

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        if: success() # or always() to upload even if previous steps fail
        with:
          # TODO runner doesn't create the static folder inside build
          sarif_file: ${{ github.workspace }}/build
