name: Static Analysis
run-name: ${{ github.actor }}-${{github.repository}} Static Analysis

on:
    schedule:
      - cron: "0 4 * * *"   # <=== Change this value

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
            options: |
            CMAKE_BUILD_TYPE=Static